Move contributor ladder from drafts to live
cncf/project-template pull request #9
Opened 2021-05-12 18:30 UTC by carolynvs

* Move contributor ladder to main branch
* Rename to CONTRIBUTOR_LADDER.md
* Fix typos

2021-05-13 09:49 UTC, geekygirldawn requested changes
I was proposing a slightly stripped down version this contributor ladder for another project, and while I was using the template, I noticed a few typos, which I've included here in the review.

I also got a comment from someone who didn't believe that it was implementable using GitHub's permissions. I made some suggestions for how to do it, but I guess maybe it isn't obvious to others? I wonder if we need some comments or maybe a companion document that provides some guidance about how this maps to GitHub permissions or pointers to things like Prow? This shouldn't gate the template going out, but it might be something we should think about improving later.

2021-05-13 09:49 UTC, geekygirldawn commented on contributor-ladder.md
> +Hello! We are excited that you want to learn more about our project contributor ladder! This contributor ladder outlines the different contributor roles within the project, along with the responsibil
Typo in responsibilities.

2021-05-13 09:49 UTC, geekygirldawn commented on contributor-ladder.md
> +<!-- This role describes people who have just started contributing, or who contribute occasionally but don't participate in project governance or have defined responsibilities.  Usually projects defi
Typo in define

2021-05-13 09:49 UTC, geekygirldawn commented on contributor-ladder.md
> +An Organization Member must meet the responsibilites and has the requirements of a Contributor, plus:
Typo in responsibilities

2021-05-13 09:49 UTC, geekygirldawn commented on contributor-ladder.md
> +Involuntary removal/demotion of a contributor happens when responsibilites and requirements aren't being met. This may include repeated pattern of inactivity, extended period of inactivity, a period
Typo in responsibilities

2021-05-13 09:49 UTC, geekygirldawn commented on contributor-ladder.md
> +    * Continues to contribute regularly, as demonstrated by having at least [TODO: Number] [TODO: Metric] a year, as demonstrated by [TODO: contributor metrics source]. <!-- Example: "as demonstrated
We should fix the capitalization of GitHub throughout.

2021-05-13 09:49 UTC, geekygirldawn commented on contributor-ladder.md
> +    * Must have successful contribitons to the project, including at least one of the following:
Typo in contributions

2021-05-13 09:49 UTC, geekygirldawn commented on contributor-ladder.md
> +    * Reviewing most Pull Requests against their specific areas of responsiblity
Typo in responsibility

2021-05-13 15:04 UTC, carolynvs commented
I am incapable of spotting typos so I am very grateful @geekygirldawn that you are catching them! 👍

2021-05-13 16:57 UTC, carolynvs commented
Yeah we do have a GitHub section on the site where we could add task oriented docs on things like bots and security/config. What do you think?

https://contribute.cncf.io/maintainers/github/

2021-05-14 22:24 UTC, jberkus commented
@geekygirldawn "I also got a comment from someone who didn't believe that it was implementable using GitHub's permissions."

What does "it" refer to here?  Not following.

2021-05-14 22:27 UTC, jberkus approved these changes
Looks good, thanks for typo fixes!

2021-05-14 22:28 UTC, jberkus commented
> Yeah we do have a GitHub section on the site where we could add task oriented docs on things like bots and security/config. What do you think?
> 
> https://contribute.cncf.io/maintainers/github/

yeah, I think that's the right place for GH-specific implementation details of stuff like "Org Member".

2021-05-17 14:32 UTC, carolynvs commented
@geekygirldawn I've fixed the problems you identified, can you take another look?

2021-05-18 09:10 UTC, geekygirldawn approved these changes
I find one more little typo, but overall this looks really good!

2021-05-18 09:10 UTC, geekygirldawn commented on CONTRIBUTOR_LADDER.md
> +1. The contributor is nominated by opening a PR against the appropriate repository, which adds the to the OWNERS file for one or more directories.
Looks like this is missing a word. Probably

... adds the GitHub id to the OWNERS file ...

2021-05-18 13:59 UTC, carolynvs commented
I don't wan to keep pushing changes to the live drafts branch, so I've created a new PR to finish this.

2021-05-18 13:59 UTC, closed without merging